development:
  adapter: postgresql
  database: rsig_development
  host: localhost
  port: 5434
  username: postgres
  password: postgres

test: &TEST
  adapter: postgresql
  database: rsig_test
  host: localhost
  port: 5434
  username: postgres
  password: postgres

production:
  adapter: postgresql
  database: rsig_production
  host: localhost
  username: postgres
  password: postgres


cucumber:
  <<: *TEST
